cats_database/config/routes.rb
Rails.application.routes.draw do

  get 'import/show_form'
  post 'import/review'
  get 'import/review'
  post 'import/perform'
  post 'import/decline'

  get 'raise/exception'
  get 'import', to: 'import#index', as: 'imports'
  
  resources :customers
  resources :orders

  resources :cats do
    post 'notify', on: :member
  end

#  resoures :dogs
#  get 'cats/:id/notify', to: 'cats#notify', as: 'notify_cat'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

cats_database/app/controllers/import_controller.rb
class ImportController < ApplicationController
  def show_form
  end

  def review
    @import_id = Random.rand(2**31)
    xlsx = Roo::Spreadsheet.open(params[:file].tempfile.path)
    sheets = []; xlsx.each_with_pagename { |name, sheet| sheets << sheet }
    @data = []
    sheets.first.each{|row| @data << row}
    
    @data.each_with_index do |row, idx|
      next if idx < 1
      customer = Customer.create(email: row[0], firstname: row[1], lastname: row[2], import_id: @import_id)
      if customer.persisted?
        Order.create(name: row[3], customer: customer, import_id: @import_id)
      else
        Order.create(name: row[3], customer: Customer.find_by(email: row[0]), import_id: @import_id)
      end
    end
 
    @customers = Customer.all
  end

  def index
      @customers = Customer.where(import_id: nil).all
  end

  def perform
    Customer.where(import_id: params[:import_id]).update_all(import_id: nil)
    Order.where(import_id: params[:import_id]).update_all(import_id: nil)
    redirect_to imports_path
  end

  def decline
    Customer.where(import_id: params[:import_id]).delete_all
    Order.where(import_id: params[:import_id]).delete_all
    redirect_to imports_path
  end
end

cats_database/app/helpers/import_helper.rb
module ImportHelper
end

cats_database/app/views/import/index.html.haml
%h1 Import index
%table
  - @customers.each do |customer|
    %tr
      %td= customer.email
      %td= customer.firstname
      %td= customer.lastname
      %td
        - customer.orders.each do |order|
          = order.name

cats_database/app/views/import/perform.html.erb
<h1>Import#perform</h1>
<p>Find me in app/views/import/perform.html.erb</p>

cats_database/app/views/import/review.html.haml
%h1 Import#review
= debug @data
%table
  - @customers.each do |customer|
    - customer.valid?
    %tr
      %td{style: "background-color: #{customer.errors.messages.keys.include?(:email) ? 'red' : 'white'}"}= best_in_place customer, 'email'
      %td{style: "background-color: #{customer.errors.messages.keys.include?(:firstname) ? 'red' : 'white'}"}= best_in_place customer, 'firstname'
      %td{style: "background-color: #{customer.errors.messages.keys.include?(:lastname) ? 'red' : 'white'}"}= best_in_place customer, 'lastname'
      %td
        - customer.orders.each do |order|
          - order.valid?
          %span{style: "background-color: #{order.errors.messages.keys.include?(:name) ? 'red' : 'white'}"}= best_in_place order, 'name'
= link_to 'Confirm', import_perform_path(import_id: @import_id), method: :post
= link_to 'Decline', import_decline_path(import_id: @import_id), method: :post

cats_database/app/views/import/show_form.html.erb
<%= form_tag import_review_path, method: :post, multipart: true do %>
  <%= file_field_tag 'file' %>
  <label>User:</label>
  <%= text_field_tag 'user', 'John'%>
  <%= submit_tag %>
<% end %>