cats_database/config/routes.rb
Rails.application.routes.draw do

  get 'import/show_form'
  post 'import/review'
  get 'import/review'
  post 'import/perform'
  post 'import/decline'

  get 'raise/exception'
  get 'import', to: 'import#index', as: 'imports'
  
  resources :customers
  resources :orders

  resources :cats do
    post 'notify', on: :member
  end

#  resoures :dogs
#  get 'cats/:id/notify', to: 'cats#notify', as: 'notify_cat'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

cats_database/app/models/cat.rb
class Cat < ApplicationRecord
  def fans
    ['me@domain.tld', 'you@yourdomain.tld']
  end
end

cats_database/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy, :notify]

  def notify
    notice = 'Notification was sent'
    begin
      email = NotiierMailer.with(cat: @cat).kittens.deliver
    rescue Errno::ECONNREFUSED => e
      notice = "Mail was not sent #{e.inspect}"
    end
    redirect_to @cat, notice: notice
  end

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name, :age, :sex)
    end
end

cats_database/app/helpers/cats_helper.rb
module CatsHelper
end

cats_database/app/views/cats/_form.html.erb
<%= form_with(model: cat, local: true) do |form| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.check_box :sex %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

cats_database/app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

cats_database/app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Sex</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.name %></td>
        <td><%= cat.age %></td>
        <td><%= cat.sex %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Notify', notify_cat_path(cat), method: :post %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

cats_database/app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

cats_database/app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @cat, :name, tabindex: "1" %>
</p>

<p>
  <strong>Age:</strong>
  <%= @cat.age %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @cat.sex %>
</p>

<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>